name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]
  workflow_dispatch:

jobs:
  # Lint job - required for branch protection
  lint:
    name: Code Quality & Linting
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run ESLint
      run: npm run lint
      continue-on-error: false
      
    - name: Run Prettier check
      run: npm run prettier:check
      continue-on-error: false

  # Test job - required for branch protection
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [18] # Temporarily remove Node.js 20 for debugging
        
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Clear MongoDB binaries cache
      run: |
        sudo rm -rf /tmp/mongo-binaries-* || true
        sudo rm -rf /home/runner/.cache/mongodb-binaries || true
        sudo find /tmp -name "*.lock" -path "*mongo*" -delete || true
      
    - name: Setup CI environment
      run: |
        echo "GITHUB_RUN_ID=${{ github.run_id }}" >> $GITHUB_ENV
        echo "CI=true" >> $GITHUB_ENV
        echo "NODE_ENV=test" >> $GITHUB_ENV
        
    - name: Predownload MongoDB binaries
      run: npm run ci:setup
      working-directory: ./backend
      
    - name: Run unit tests
      run: npm run test:unit
      working-directory: ./backend
      env:
        GITHUB_RUN_ID: ${{ github.run_id }}
        CI: true
        NODE_ENV: test
      
    - name: Run integration tests
      run: npm run test:integration
      working-directory: ./backend
      env:
        GITHUB_RUN_ID: ${{ github.run_id }}
        CI: true
        NODE_ENV: test
      
    - name: Upload coverage reports
      if: success()
      uses: codecov/codecov-action@v3
      with:
        file: ./backend/coverage/lcov.info
        fail_ci_if_error: false

  # Build job - required for branch protection
  build:
    name: Build Application
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Build applications
      run: npm run build
      
    - name: Check build outputs
      run: |
        echo "Frontend dist contents:"
        ls -la frontend/dist/ || echo "Frontend dist directory not found"
        echo "Backend dist contents:"
        ls -la backend/dist/ || echo "Backend dist directory not found"
        
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          frontend/dist/
          backend/dist/
        if-no-files-found: warn

  # Security scan job
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run npm audit
      run: npm audit --audit-level=moderate
      continue-on-error: true
      
  # Type checking (for TypeScript projects)
  typecheck:
    name: Type Check
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Type check frontend
      run: npm run typecheck:frontend
      
    - name: Type check backend
      run: npm run typecheck:backend

  # Deploy job (only on main branch)
  deploy:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [lint, test, build, security, typecheck]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    
    environment:
      name: production
      url: https://your-app-url.com
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        
    - name: Deploy to Railway/Render
      run: |
        echo "Deploy to production"
        # Add your deployment commands here
        
  # Deploy staging (only on develop branch)
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: [lint, test, build, security, typecheck]
    if: github.ref == 'refs/heads/develop' && github.event_name == 'push'
    
    environment:
      name: staging
      url: https://staging-your-app-url.com
      
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        
    - name: Deploy to staging
      run: |
        echo "Deploy to staging"
        # Add your staging deployment commands here 